### ISSUE TITLE
No podspec found

### ISSUE THREAD

**Issue by mrnicon** [khp53/flutter_star_prnt_plus#1]
I get this error on compiling for ios 
!] No podspec found for `flutter_star_prnt_plus` in `.symlinks/plugins/flutter_star_prnt_plus/ios`

Is this related to the package or is is it me doing something wrong? 
Is it possible the naming that is wrong in the podspec file?

**Comment by mrnicon** [comment]
do we need to change the s.name in ios/flutter_star_prnt.podspec ?

**Comment by khp53** [comment]
@mrnicon I will look into this issue over the weekend, and will update you. Thank you.

**Comment by khp53** [comment]
@mrnicon For now change the name of the podspec file to "flutter_star_prnt_plus.podspec" and inside the file change the s.name to "flutter_star_prnt_plus".

**Comment by mrnicon** [comment]
@khp53  I get this error on trying to compile, it might be related: 
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'flutter_star_prnt-Swift.h' file not found
/Users/builder/.pub-cache/hosted/pub.dev/flutter_star_prnt_plus-2.4.3/ios/Classes/FlutterStarPrntPlugin.m:7:8
