### ISSUE TITLE
Problem building for iOS

### ISSUE THREAD

**Issue by cgutierr-zgz** [khp53/flutter_star_prnt_plus#2]
Hi!
I'm having some trouble building for iOS

Output:
```text
Launching lib/main.dart on xxx in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: xxx
Xcode build done.                                           15,5s
Failed to build iOS app
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'flutter_star_prnt-Swift.h' file not found
/Users/xxx/.pub-cache/hosted/pub.dev/flutter_star_prnt_plus-2.4.3/ios/Classes/FlutterStarPrntPlugin.m:7:8
2

Error launching application on xxx
```

Also, could we get some more docs on how to do some other prints/cuts/open drawer?
Thanks a lot!

**Comment by khp53** [comment]
@cgutierr-zgz Alright, I will look into that, and hopefully soon will add some more docs.

**Comment by khp53** [comment]
@cgutierr-zgz Fixed and working perfectly now, please update to version 2.4.4.

**Comment by mrnicon** [comment]
@khp53 can you confirm that printing from a Iphone is working, as the code compile fine, but I get no port to print to. ( I have tried all kinds of setup) And the Star setup app is printing just fine.

**Comment by cgutierr-zgz** [comment]
> @cgutierr-zgz Fixed and working perfectly now, please update to version 2.4.4.

Thanks a lot kph53!
Quick question, do u happen to know how the `openCashDrawer` works?
I can't seem to get it working
The info mentions:

```
dynamic openCashDrawer(int actionNumber)
open cash drawer, [actionNumber] needed to based on the printer port
```

I can't seem to find what that "action Number" is supposed to be ^^'

**Comment by khp53** [comment]
@mrnicon Printing from iPad is working, I am discovering Bluetooth and USB star 143 printers and printing perfectly. Nothing has changed from the original package in the printing section, so there is no reason for it to not work.

**Comment by khp53** [comment]
@cgutierr-zgz This is how I implemented
`PrintCommands commands = PrintCommands();
      commands.openCashDrawer(1);`
So, port number is which port your printer is in, I hardcoded the port number to 1 for now.
