### ISSUE TITLE
Gradle/Kotlin version to low

### ISSUE THREAD

**Issue by mrnicon** [khp53/flutter_star_prnt_plus#3]
I get this error on trying to compile a APK 

Upgrading build.gradle
Running Gradle task 'bundleRelease'...
FAILURE: Build failed with an exception.
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_star_prnt_plus' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

I found some trace that might help in:  android/build.gradle
Is it possible to upgrade this to a later version?

**Comment by mrnicon** [comment]
@khp53 is it possible to upgrade the gradle version to later then 1.5.20?

**Comment by khp53** [comment]
@mrnicon Let me check first.

**Comment by mrnicon** [comment]
I am still not able to compile my project as the gradle is of a older version. 
@khp53 any updates?

**Comment by khp53** [comment]
Oh I did not see the past comments! I will make sure to update it tomorrow!

**Comment by khp53** [comment]
@mrnicon updated package
